name: Build & Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build Theme Assets
        run: npm run build

      # Optional: Test rendering with resumed (requires a sample resume.json)
      - name: Install resumed globally
        run: npm install -g resumed

      - name: Test render default resume
        # Ensure a default resume.json exists for this test
        if: hashFiles('resume.json') != ''
        run: npm run render:local

      - name: Check if output exists
        if: hashFiles('resume.json') != ''
        run: test -f test-output.html && echo "Render test passed"
